Subfeature/infrastructure minor impovements
Beta-dating/web-api pull request #5
Opened 2024-06-01 07:44 UTC by yunikeil

@pavelepanov проверяй, тут без апишки пока что

2024-06-01 08:08 UTC, pavelepanov requested changes

2024-06-01 08:08 UTC, pavelepanov commented on src/beta/infrastructure/data_access/models/base.py
Ты уверен, что добавление created_at в базовый класс является интуитивно понятным решением? 
Если, например, нам нужно будет добавить updated_at?
Модели пишутся по диаграммам, не стоит думать о том, что какое-то поле где-то указано в базовом классе. Мы люди и можем ошибиться. 
Думаю, лучше указать явно в каждой модели поле created_at.

2024-06-01 08:13 UTC, yunikeil commented on src/beta/infrastructure/data_access/models/base.py
Ну вообще если поле есть во всех таблицах, то почему бы и не вынести его один раз отдельно?
В диаграммах можно указать на наличие базового класса, но могу и везде задать, не проблема)

2024-06-02 10:42 UTC, merged

2024-06-02 11:20 UTC, kir-sth commented on src/beta/infrastructure/data_access/models/base.py
Мне тоже нравится вынести в Base класс, потому что это технические достаточно поля, нужны для аналитики